// <auto-generated />
namespace ItAcademy.SchoolAdmin.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class InsertPhonesData : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InsertPhonesData));
        
        string IMigrationMetadata.Id
        {
            get { return "202007091113202_InsertPhonesData"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
