// <auto-generated />
namespace ItAcademy.SchoolAdmin.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class RemovePhoneFromEmployeeModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RemovePhoneFromEmployeeModel));
        
        string IMigrationMetadata.Id
        {
            get { return "202007171747022_RemovePhoneFromEmployeeModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
